#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'args_parser'
require 'tmp_cache'
require 'json'
require 'eventmachine'
require 'evma_httpserver'
require File.expand_path 'bootstrap', File.dirname(__FILE__)
Bootstrap.init :libs

parser = ArgsParser.parse ARGV do
  arg :list, 'show chat list'
  arg :port, 'http port', :default => 8787
  arg :conf, 'config file', :default => File.expand_path('config.yml', File.dirname(__FILE__))
  arg :help, 'show help', :alias => :h
end

if parser.has_option? :help
  puts parser.help
  puts "e.g.  #{$0} -help"
  puts "e.g.  #{$0} -chat '#foo/$bar;a1b2cde345'"
  exit
end

Conf.conf_file = parser[:conf]

if parser.has_option? :list
  SkypeGateway::Skype.recent_chats.each do |c|
    puts c
  end
  exit
end

SkypeGateway::HttpServer.chats = Conf['chats']
unless Conf['chats'].empty?
  puts "--chat aliases--"
  Conf['chats'].each do |k,v|
    puts "- #{k} => #{v}"
  end
  puts "----"
end

EM::run do
  EM::start_server('0.0.0.0', parser[:port].to_i, SkypeGateway::HttpServer)
  puts "start HTTP server - port #{parser[:port].to_i}"
end
