#!/usr/bin/env ruby
require 'rubygems'
require 'ArgsParser'
require 'rb-skypemac'
require 'eventmachine'
require 'evma_httpserver'
require 'json'

def skype(command)
  SkypeMac::Skype.send_(:command => command)
end

class SkypeHttpServer  < EM::Connection
  include EM::HttpServer
  
  def process_http_request
    res = EM::DelegatedHttpResponse.new(self)
    puts "* http #{@http_request_method} #{@http_path_info} #{@http_query_string} #{@http_post_content}"
    if @http_request_method == 'POST'
      puts cmd = "chatmessage #{@@chat_id} #{@http_post_content}"
      res.content = skype cmd
      res.status = 200
      res.send_response
    elsif @http_request_method == 'GET'
      puts cmd = "get chat #{@@chat_id} recentchatmessages"
      ids = skype(cmd).split(/,* /).delete_if{|i|
        !(i =~ /^\d+$/)
      }.map{|i|
        i.to_i
      }.sort.reverse
      chats = ids.map{|id|
        {
          :id => id,
          :user => skype("get chatmessage #{id} from_handle").split(/ /).last,
          :body => skype("get chatmessage #{id} body").split(/ /).last,
          :time => skype("get chatmessage #{id} timestamp").split(/ /).last.to_i
        }
      }
      res.status = 200
      res.content = chats.to_json
      res.send_response
    end
  end
end

parser = ArgsParser.parser
parser.comment(:port, 'http port', 8787)
parser.comment(:chat, 'chat id')
parser.bind(:help, :h, 'show help')

first, params = parser.parse ARGV

if parser.has_option(:help)
  puts parser.help
  puts "#{$0} -> get chat list"
  puts "#{$0} -chat -> "
  exit
end

if !parser.has_param(:chat)
  skype('SEARCH RECENTCHATS').split(/,* /).each do |c|
    puts c
  end
  exit
end

@@chat_id = params[:chat]
puts "chat : #{@@chat_id}"



EM::run do
  EM::start_server('0.0.0.0', params[:port].to_i, SkypeHttpServer)
  puts "start HTTP server - port #{params[:port].to_i}"
end



